# Generated by Django 3.1.14 on 2023-02-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20230221_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='photo',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
